### ISSUE TITLE
Crashes while downloading

### ISSUE THREAD

**Issue by seichr** [laurensk/digi4school-pdf#1]
When using the program as described the following error crashes the program every time:

(node:17808) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '
split' of undefined
    at Function.<anonymous> (C:\Users\Christian\Documents\digi4school-pdf\dist\D
4SBookProperties.js:49:53)
    at Generator.next (<anonymous>)
    at C:\Users\Christian\Documents\digi4school-pdf\dist\D4SBookProperties.js:8:
71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Christian\Documents\digi4school-pdf\dist\D4SBookPrope
rties.js:4:12)
    at Request._callback (C:\Users\Christian\Documents\digi4school-pdf\dist\D4SB
ookProperties.js:27:26)
    at Request.self.callback (C:\Users\Christian\Documents\digi4school-pdf\node_
modules\request\request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (C:\Users\Christian\Documents\digi4school-pdf\node_mo
dules\request\request.js:1154:10)
    at Request.emit (events.js:314:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17808) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
 error originated either by throwing inside of an async function without a catch
 block, or by rejecting a promise which was not handled with .catch(). To termin
ate the node process on unhandled promise rejection, use the CLI flag `--unhandl
ed-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejecti
ons_mode). (rejection id: 1)
(node:17808) [DEP0018] DeprecationWarning: Unhandled promise rejections are depr
ecated. In the future, promise rejections that are not handled will terminate th
e Node.js process with a non-zero exit code.

Running this on Windows 10 and all of the Requirements are installed.

Maybe there's a workaround or something.

Best Regards
Christian

**Comment by laurensk** [comment]
Hey Christian!

Thanks for reaching out to me. First, I want you to see this project as a proof-of-concept, so this is by no means a finished or production-ready code.

Digi4school has recently deployed new ways for books to be displayed in the frontend and this could lead to this error. Maybe you can try a different book to see if that's the case. I absolutely try to implement all new features to make this project work in the future but sadly, there are just too many things to implement and since downloading books from Digi4school is illegal, I don't set high priority for this.

I hope I could clarify!
Let me know if there is anything else I can do!

All the best,
Laurens

**Comment by seichr** [comment]
Hey Laurens,

Thanks for replying so fast! I definitelly get that! Thanks for providing this Proof-Of-Concept!

All of my Books lead to this error-behaviour. I totally get that you do not prioritize this side project I was just hoping that you would know this problem and a quick fix for it.

I'll close the Issue with this comment! Thanks for your answer!

Best regards
Christian
